# Site settings
url: http://www.klaascuvelier.be
name: Klaas Cuvelier
email: cuvelierklaas@gmail.com
title: Klaas C.
description: > # this means to ignore newlines until "baseurl:"
  Home page of Klaas Cuvelier. Full stack developer, runner and geek.
  This is where I share stuff I consider worth sharing.
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: klaascuvelier
github_username:  klaascuvelier
url: "http://blog.klaascuvelier.be/"
google_analytics: "UA-2458471-3"
animated: false
show_related_posts: false
paginate: 10
paginate_path: "/page:num/"
permalink: /:year/:month/:title

# Build settings
markdown: kramdown

