# Site settings
url: http://www.klaascuvelier.be
name: Klaas Cuvelier
email: cuvelierklaas@gmail.com
description: Things I find worth sharing
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: klaascuvelier
github_username:  klaascuvelier
url: "http://blog.klaascuvelier.be/"
google_analytics: "UA-2458471-3"
animated: false
show_related_posts: false
paginate: 10
paginate_path: "/page:num/"
permalink: /:year/:month/:title

# Build settings
markdown: kramdown

